### ISSUE TITLE
conf_m of LDA

### ISSUE THREAD

**Issue by guin0x** [emredjan/ISL-python#1]
Hi, I started doing this course - and similar to you, I want to implement it in Python.
I was going through your code and on the Notebook *lab_04.6_logistic_regression_lda_qda_knn*, if you scroll down to the **4.6.3 Linear Discriminant Analysis**, I think there is a mistake in the code.

When getting the confusion matrix of the LDA you have the line `conf_m = pd.DataFrame(confusion_matrix(y_test, glm_fit.predict(X_test)))`, but I believe you meant to have `lda_fit.predict(X_test)`? Since this section is for LDA, the `glm_fit.predict()` was used before in the Logistic Regression part.

**Comment by emredjan** [comment]
You're right, thanks for catching that. Probably forgot to change as I was reusing code between similar sections. Goes to show it's better to put code in functions :)

Fixed now with  [51c277a](https://github.com/emredjan/ISL-python/commit/51c277a4a40ab15bb9f0e73ef2d01a25faa363d0)

**Comment by guin0x** [comment]
Nice. Quick fix. :)

I see that you wrote these Notebooks 5 years ago, so many things have
changed (such as `pd.set_option('precision')` to
`pd.set_option('display.precision')`)

Is there any interest in updating these Notebooks? I have downloaded all of
them and I will follow and fix whatever I find wrong in my versions...

I also have a plan in doing the exercises, and I see you didn't do all of
them.

If you have interest in updating them, I could send them to you?

Thanks!

Kind regards,

Gui Alvarenga
Mobile: +31 6 33 29 65 22

**Comment by emredjan** [comment]
Yeah, these were kind of learning exercises for myself, I'm just glad so many people found them useful. 

There's even a newer edition of the book I believe, with some expanded content. A couple of people also asked me if I was planning to update the repository, but I'm not sure I'll have the time. 

I appreciate any updates though. You can also fork the repository and make your changes and submit a pull request, I'd be happy to include them.

_(Edited for grammar)_

**Comment by guin0x** [comment]
Great!
I'll see what I can do.

Kind regards,

Gui Alvarenga
Mobile: +31 6 33 29 65 22
